### PR TITLE
Update ML scripts (csv output), update makefile, change ML to ipynb files

### PR DESCRIPTION
**Pull request by nicovandenhooff**

### CODE REVIEW

**Comment by ytz** [comment]
Hey @nicovandenhooff, sorry I'm on mobile. I reviewed some of the changes. I'm not sure whether you have overwritten some of my changes in data analysis md

**Review by arijeetchatterjee — APPROVED** [review]

**Comment by nicovandenhooff** [comment]
Hey @ytz 

I was looking at our commit history and couldn't seem to find the change where the changes were made to the data analysis md file, could you take a quick look and let me know if you can identify the commit?  Thanks

**Comment by nicovandenhooff** [comment]
Hey @ytz - so I was looking at the commit where the changes were made to the data analysis `md` file:

https://github.com/UBC-MDS/online-shoppers-purchasing-intention/commit/9e585884b11548d28df90e4ded0c881dd8cc71f3

I'm not sure if the actual `md` file itself was pushed to the repo, it looks like only the changes in the Jupyter book made it through, but let me know if I'm wrong!  Anyways I think its an easy fix, we just need to update the `md` file to have your analysis in it.

**Comment by ytz** [comment]
@nicovandenhooff yea I think you're right. Let me find the actual md file. I'll merge this PR first

**Review by ytz — APPROVED** [review]

**Pull request merged**
